name = "nexus-agent-brain"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "NEXUS_AGENT"
id = "c3c0582ec71c4d049d0795872f39f033"

[triggers]
crons = ["*/5 * * * *"]

[observability.logs]
enabled = true
invocation_logs = true
